baseURL = "https://gemea.ise.fiz-karlsruhe.de/"
theme   = "blowfish"

defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength   = 0
enableEmoji     = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag      = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[imaging]
  anchor = "Center"
