[[main]]
  name       = "Corpus"
  pageRef    = "/corpus"
  weight     = 10

[[main]]
  name       = "Architecture"
  pageRef    = "/architecture"
  weight     = 20

[[main]]
  name       = "Paper"
  pageRef    = "/paper"
  weight     = 30

[[main]]
  name       = "Data Stories"
  pageRef    = "/data-stories"
  weight     = 40

[[main]]
  name       = "GitHub"
  url        = "https://github.com/ise-fizkarlsruhe/gemea"
  weight     = 50
  [main.params]
    icon     = "github"
    showName = false
    target   = "_blank"

[[main]]
  name       = "SHMARQL"
  url        = "https://gemea.ise.fiz-karlsruhe.de/shmarql/"
  weight     = 60
  [main.params]
    icon     = "link"
    showName = true
    target   = "_blank"
