# Purpose:      Generate fig_title_lengths.jsx and fig_title_lengths_bw.html
#               from the title-length-analysis.json produced by
#               sr10_analyse_title_lengths.py.
# Usage:        python scripts/sr10_render_title_viz.py
#               python scripts/sr10_render_title_viz.py --json PATH --output-dir PATH
# Inputs:       notes/images/title-length-analysis.json  (or --json)
# Outputs:      <output-dir>/fig_title_lengths.jsx
#               <output-dir>/fig_title_lengths_bw.html
# Dependencies: none (stdlib only)
# Assumptions:  JSON was produced by sr10_analyse_title_lengths.py and contains
#               a 'bucketed' key with per-period counts and medians.

import argparse
import json
from pathlib import Path

# ── JSX template ──────────────────────────────────────────────────────────────
# Self-contained React component; reads data via ES module import.

JSX = r"""/**
 * fig_title_lengths.jsx
 *
 * Library of leather-bound books visualizing DDB title token lengths
 * by 25-year period.
 *
 *   Height of each book  →  number of objects in the period
 *   Leather patina       →  median title length in tokens
 *
 * Data source: title-length-analysis.json  (scripts/sr10_analyse_title_lengths.py)
 * Generated by: scripts/sr10_render_title_viz.py
 * Usage: import and render <TitleLengthLibrary /> in any React app.
 */

import React, { useRef, useState } from 'react';
import rawData from './title-length-analysis.json';

// ── layout constants ──────────────────────────────────────────────────────────

const BOOK_W    = 44;
const BOOK_GAP  = 5;
const MAX_BOOK_H = 300;
const MIN_BOOK_H = 28;
const SHELF_Y   = 415;
const START_X   = 60;
const SVG_H     = 510;

// ── colour helpers ────────────────────────────────────────────────────────────

/**
 * Map median token count (data range: 6–15) to a leather HSL colour.
 *   t = 0  →  pale tan        (short modern titles, lightly patinated)
 *   t = 1  →  dark mahogany   (long baroque titles, heavily patinated)
 */
function patina(median) {
  const t = Math.min(1, Math.max(0, (median - 6) / 9));
  const h = (27 - t * 12).toFixed(1);   // 27° warm tan → 15° mahogany
  const s = (45 + t * 23).toFixed(1);   // 45% → 68%
  const l = (54 - t * 34).toFixed(1);   // 54% → 20%
  return `hsl(${h},${s}%,${l}%)`;
}

function patinaHighlight(median) {
  const t = Math.min(1, Math.max(0, (median - 6) / 9));
  const h = (27 - t * 12).toFixed(1);
  const s = (30 + t * 15).toFixed(1);
  const l = (68 - t * 28).toFixed(1);
  return `hsl(${h},${s}%,${l}%)`;
}

function fmt(n) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000)     return `${(n / 1_000).toFixed(1)}k`;
  return String(n);
}

// ── component ─────────────────────────────────────────────────────────────────

export default function TitleLengthLibrary() {
  const containerRef = useRef(null);
  const [tooltip, setTooltip]   = useState(null);

  const buckets = Object.entries(rawData.bucketed)
    .filter(([, v]) => v.total > 100)
    .map(([label, v]) => ({ label, ...v }));

  const maxTotal = Math.max(...buckets.map(b => b.total));
  const SVG_W = START_X * 2 + buckets.length * (BOOK_W + BOOK_GAP) - BOOK_GAP;

  const bookH = (total) => Math.max(MIN_BOOK_H, (total / maxTotal) * MAX_BOOK_H);

  function handleMouseMove(e, book) {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    setTooltip({ book, x: e.clientX - rect.left + 14, y: e.clientY - rect.top - 10 });
  }

  return (
    <div
      ref={containerRef}
      style={{ position: 'relative', display: 'inline-block', background: '#0f0804' }}
    >
      <svg width={SVG_W} height={SVG_H} viewBox={`0 0 ${SVG_W} ${SVG_H}`}
           style={{ display: 'block' }}>
        <defs>
          {/* Leather grain: faint diagonal scratches */}
          <pattern id="grain" width="4" height="60" patternUnits="userSpaceOnUse">
            <line x1="1"   y1="0" x2="0.5" y2="60"
                  stroke="rgba(0,0,0,0.09)"       strokeWidth="0.6"/>
            <line x1="3.2" y1="0" x2="2.8" y2="60"
                  stroke="rgba(255,255,255,0.04)"  strokeWidth="0.4"/>
          </pattern>

          {/* Worn oak shelf */}
          <linearGradient id="shelf" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%"   stopColor="#7a4e22"/>
            <stop offset="18%"  stopColor="#5c3510"/>
            <stop offset="100%" stopColor="#2a1508"/>
          </linearGradient>

          {/* Dark oak-panel wall */}
          <linearGradient id="wall" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%"   stopColor="#1c0d06"/>
            <stop offset="100%" stopColor="#0f0804"/>
          </linearGradient>
        </defs>

        {/* ── background ─────────────────────────────────────────────────── */}
        <rect width={SVG_W} height={SVG_H} fill="url(#wall)"/>

        {/* Subtle horizontal panelling lines */}
        {Array.from({ length: 7 }, (_, i) => (
          <line key={i}
                x1="0" y1={i * 65 + 65} x2={SVG_W} y2={i * 65 + 65}
                stroke="rgba(255,255,255,0.012)" strokeWidth="1"/>
        ))}

        {/* ── books ──────────────────────────────────────────────────────── */}
        {buckets.map((b, i) => {
          const bh  = bookH(b.total);
          const bx  = START_X + i * (BOOK_W + BOOK_GAP);
          const by  = SHELF_Y - bh;
          const base = patina(b.median_all_tokens);
          const hl   = patinaHighlight(b.median_all_tokens);

          return (
            <g key={b.label}
               onMouseMove={(e) => handleMouseMove(e, b)}
               onMouseLeave={() => setTooltip(null)}
               style={{ cursor: 'crosshair' }}>

              {/* Drop shadow */}
              <rect x={bx + 3} y={by + 3} width={BOOK_W} height={bh}
                    fill="rgba(0,0,0,0.5)" rx="2"/>

              {/* Book body */}
              <rect x={bx} y={by} width={BOOK_W} height={bh}
                    fill={base} rx="2" ry="2"/>

              {/* Leather grain overlay */}
              <rect x={bx} y={by} width={BOOK_W} height={bh}
                    fill="url(#grain)" rx="2" opacity="0.75"/>

              {/* Left spine highlight — light catches the raised edge */}
              <rect x={bx} y={by} width={5} height={bh}
                    fill={hl} rx="2" opacity="0.55"/>

              {/* Right edge shadow */}
              <rect x={bx + BOOK_W - 4} y={by} width={4} height={bh}
                    fill="rgba(0,0,0,0.35)" rx="2"/>

              {/* Top cap */}
              <rect x={bx} y={by} width={BOOK_W} height={4}
                    fill={hl} rx="2" opacity="0.65"/>

              {/* Bottom foot — binding wear */}
              <rect x={bx + 1} y={by + bh - 6} width={BOOK_W - 2} height={6}
                    fill="rgba(0,0,0,0.25)" rx="1"/>

              {/* Spine label — two horizontal lines at the bottom */}
              {(() => {
                const [start, end] = b.label.split('\u2013');
                const cx      = bx + BOOK_W / 2;
                const bottomY = by + bh - 7;
                const fill    = 'rgba(255,215,110,0.62)';
                const props   = { fill, fontSize: '7', fontFamily: "Georgia,'Times New Roman',serif", textAnchor: 'middle' };
                return (
                  <>
                    <text x={cx} y={bottomY - 9} {...props}>{start} –</text>
                    <text x={cx} y={bottomY}     {...props}>{end}</text>
                  </>
                );
              })()}
            </g>
          );
        })}

        {/* ── shelf ──────────────────────────────────────────────────────── */}
        <rect x={18} y={SHELF_Y}      width={SVG_W - 36} height={22}
              fill="url(#shelf)" rx="2"/>
        {/* Top edge highlight */}
        <rect x={18} y={SHELF_Y}      width={SVG_W - 36} height={2}
              fill="rgba(255,185,70,0.22)" rx="1"/>
        {/* Undershadow */}
        <rect x={18} y={SHELF_Y + 22} width={SVG_W - 36} height={9}
              fill="rgba(0,0,0,0.65)" rx="2"/>

        {/* ── title ──────────────────────────────────────────────────────── */}
        <text x={SVG_W / 2} y={36}
              fill="rgba(235,205,140,0.75)"
              fontSize="14"
              fontFamily="Georgia,'Times New Roman',serif"
              textAnchor="middle"
              letterSpacing="3">
          DDB TITLE TOKEN LENGTHS · 1500 – 2024
        </text>
        <text x={SVG_W / 2} y={54}
              fill="rgba(175,140,85,0.45)"
              fontSize="9"
              fontFamily="Georgia,serif"
              textAnchor="middle"
              letterSpacing="1.5">
          Height · objects per 25-year period  ·  Patina · median title length in tokens
        </text>

        {/* ── patina legend ──────────────────────────────────────────────── */}
        <text x={SVG_W - 192} y={SVG_H - 80}
              fill="rgba(185,148,82,0.6)"
              fontSize="7.5"
              fontFamily="Georgia,serif"
              letterSpacing="1.2">
          PATINA · MEDIAN TOKENS
        </text>
        {[6, 8, 10, 12, 14].map((t, i) => (
          <g key={t}>
            <rect x={SVG_W - 192 + i * 29} y={SVG_H - 70}
                  width={23} height={15} fill={patina(t)} rx="1"/>
            <text x={SVG_W - 192 + i * 29 + 11.5} y={SVG_H - 50}
                  fill="rgba(185,148,82,0.55)"
                  fontSize="8"
                  fontFamily="Georgia,serif"
                  textAnchor="middle">
              {t}
            </text>
          </g>
        ))}
        <text x={SVG_W - 192} y={SVG_H - 40}
              fill="rgba(160,125,65,0.4)"
              fontSize="7.5"
              fontFamily="Georgia,serif">
          modern
        </text>
        <text x={SVG_W - 192 + 4 * 29 + 12} y={SVG_H - 40}
              fill="rgba(160,125,65,0.4)"
              fontSize="7.5"
              fontFamily="Georgia,serif"
              textAnchor="end">
          baroque
        </text>
      </svg>

      {/* ── floating tooltip ─────────────────────────────────────────────── */}
      {tooltip && (
        <div style={{
          position:      'absolute',
          left:          tooltip.x,
          top:           tooltip.y,
          background:    'rgba(10,6,2,0.97)',
          border:        '1px solid rgba(210,165,70,0.32)',
          borderRadius:  '3px',
          padding:       '9px 13px',
          color:         '#e0c880',
          fontFamily:    "Georgia,'Times New Roman',serif",
          fontSize:      '11px',
          lineHeight:    '1.75',
          pointerEvents: 'none',
          whiteSpace:    'nowrap',
          zIndex:        20,
          boxShadow:     '0 3px 16px rgba(0,0,0,0.75)',
        }}>
          <div style={{ fontWeight: 'bold', marginBottom: 3, letterSpacing: '0.5px' }}>
            {tooltip.book.label}
          </div>
          <div>{fmt(tooltip.book.total)} objects</div>
          <div style={{ marginTop: 5, color: 'rgba(200,160,85,0.75)', fontSize: '10px' }}>
            Short  (≤ 4 tok): {fmt(tooltip.book.short)} &nbsp;
            ({((tooltip.book.short  / tooltip.book.total) * 100).toFixed(0)}%)
          </div>
          <div style={{ color: 'rgba(200,160,85,0.75)', fontSize: '10px' }}>
            Medium (5–14):    {fmt(tooltip.book.medium)} &nbsp;
            ({((tooltip.book.medium / tooltip.book.total) * 100).toFixed(0)}%)
          </div>
          <div style={{ color: 'rgba(200,160,85,0.75)', fontSize: '10px' }}>
            Long   (≥ 15 tok): {fmt(tooltip.book.long)} &nbsp;
            ({((tooltip.book.long   / tooltip.book.total) * 100).toFixed(0)}%)
          </div>
          <div style={{ marginTop: 5, color: 'rgba(185,148,75,0.6)', fontSize: '10px' }}>
            Median tokens: {tooltip.book.median_all_tokens}
          </div>
        </div>
      )}
    </div>
  );
}
"""

# ── HTML template ─────────────────────────────────────────────────────────────
# Standalone browser file: React + Babel from CDN, JSON inlined as window.TITLE_DATA.
# __JSON_DATA__ is replaced with the serialised JSON at render time.

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>DDB Title Token Lengths — B&W</title>
  <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>
    body { margin: 0; background: #e8e2d8; display: flex; justify-content: center; padding: 40px 0; }
  </style>
</head>
<body>
  <div id="root"></div>

  <script>
    window.TITLE_DATA = __JSON_DATA__;
  </script>

  <script type="text/babel">
    const { useRef, useState } = React;
    const rawData = window.TITLE_DATA;

    // ── layout ──────────────────────────────────────────────────────────────
    const BOOK_W     = 44;
    const BOOK_GAP   = 5;
    const MAX_BOOK_H = 300;
    const MIN_BOOK_H = 28;
    const SHELF_Y    = 430;
    const START_X    = 60;
    const SVG_H      = 560;

    // Historical era markers
    const ERA_MARKERS = [
      { label: 'Gutenberg',        year: 1450 },
      { label: 'Reformation',      year: 1517 },
      { label: 'French Rev.',      year: 1789 },
      { label: 'Industrialisation',year: 1840 },
      { label: 'WWI',              year: 1914 },
    ];

    // ── band base lightness and deviation encoding ───────────────────────────
    // Base: short=84% (pale), medium=52% (grey), long=20% (dark)
    // Deviation: positive (above corpus avg) → darker; negative → lighter.
    // Each band shifts ±12% lightness, keeping bands visually distinct.
    const BAND_BASE = { short: 84, medium: 52, long: 20 };
    const SPINE_HL  = 'hsl(0,0%,90%)';
    const SPINE_SH  = 'hsl(0,0%,12%)';

    function bandColor(base, dev, maxDev) {
      const t = maxDev > 0 ? dev / maxDev : 0;
      const l = Math.min(base + 12, Math.max(base - 12, base - t * 12));
      return `hsl(0,0%,${l.toFixed(0)}%)`;
    }

    function fmt(n) {
      if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
      if (n >= 1_000)     return `${(n / 1_000).toFixed(1)}k`;
      return String(n);
    }

    // ── component ───────────────────────────────────────────────────────────

    function TitleLengthLibrary() {
      const containerRef = useRef(null);
      const [tooltip, setTooltip] = useState(null);

      const buckets = Object.entries(rawData.bucketed)
        .filter(([, v]) => v.total > 100)
        .map(([label, v]) => ({ label, ...v }));

      const maxTotal = Math.max(...buckets.map(b => b.total));
      const SVG_W = START_X * 2 + buckets.length * (BOOK_W + BOOK_GAP) - BOOK_GAP;

      const bookH = (total) => Math.max(MIN_BOOK_H, (total / maxTotal) * MAX_BOOK_H);

      const corpusTotal    = buckets.reduce((s, b) => s + b.total,  0);
      const corpusShortPct = buckets.reduce((s, b) => s + b.short,  0) / corpusTotal;
      const corpusMedPct   = buckets.reduce((s, b) => s + b.medium, 0) / corpusTotal;
      const corpusLongPct  = buckets.reduce((s, b) => s + b.long,   0) / corpusTotal;
      const maxShortDev = Math.max(...buckets.map(b => Math.abs(b.short/b.total  - corpusShortPct)));
      const maxMedDev   = Math.max(...buckets.map(b => Math.abs(b.medium/b.total - corpusMedPct)));
      const maxLongDev  = Math.max(...buckets.map(b => Math.abs(b.long/b.total   - corpusLongPct)));

      function yearToX(year) {
        const firstYear = 1500;
        const bucketIdx = (year - firstYear) / 25;
        return START_X + bucketIdx * (BOOK_W + BOOK_GAP) + BOOK_W / 2;
      }

      function handleMouseMove(e, book) {
        if (!containerRef.current) return;
        const rect = containerRef.current.getBoundingClientRect();
        setTooltip({ book, x: e.clientX - rect.left + 14, y: e.clientY - rect.top - 10 });
      }

      const tallest = buckets.reduce((a, b) => b.total > a.total ? b : a);
      const tallestIdx = buckets.indexOf(tallest);
      const tallestX = START_X + tallestIdx * (BOOK_W + BOOK_GAP);
      const tallestH = bookH(tallest.total);

      return (
        <div ref={containerRef} style={{ position: 'relative', display: 'inline-block', background: '#f4f0e8' }}>
          <svg width={SVG_W} height={SVG_H} viewBox={`0 0 ${SVG_W} ${SVG_H}`}
               style={{ display: 'block' }}>
            <defs>
              <pattern id="grain" width="4" height="60" patternUnits="userSpaceOnUse">
                <line x1="1"   y1="0" x2="0.5" y2="60" stroke="rgba(0,0,0,0.07)"  strokeWidth="0.6"/>
                <line x1="3.2" y1="0" x2="2.8" y2="60" stroke="rgba(255,255,255,0.12)" strokeWidth="0.4"/>
              </pattern>
              <linearGradient id="shelf" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%"   stopColor="#6a6a6a"/>
                <stop offset="20%"  stopColor="#4a4a4a"/>
                <stop offset="100%" stopColor="#2a2a2a"/>
              </linearGradient>
              <linearGradient id="paper" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%"   stopColor="#f8f4ec"/>
                <stop offset="100%" stopColor="#ede8de"/>
              </linearGradient>
            </defs>

            <rect width={SVG_W} height={SVG_H} fill="url(#paper)"/>

            {/* ── era markers ─────────────────────────────────────────── */}
            {ERA_MARKERS.map(({ label, year }) => {
              const mx = yearToX(year);
              if (mx < START_X || mx > SVG_W - START_X) return null;
              return (
                <g key={label}>
                  <line x1={mx} y1={80} x2={mx} y2={SHELF_Y}
                        stroke="rgba(0,0,0,0.12)" strokeWidth="0.8" strokeDasharray="3,3"/>
                  <text x={mx} y={74} fill="rgba(0,0,0,0.35)" fontSize="7.5"
                        fontFamily="Georgia,serif" textAnchor="middle" letterSpacing="0.3">
                    {label}
                  </text>
                  <text x={mx} y={83} fill="rgba(0,0,0,0.25)" fontSize="7"
                        fontFamily="Georgia,serif" textAnchor="middle">
                    {year}
                  </text>
                </g>
              );
            })}

            {/* ── books ───────────────────────────────────────────────── */}
            {buckets.map((b, i) => {
              const bh = bookH(b.total);
              const bx = START_X + i * (BOOK_W + BOOK_GAP);
              const by = SHELF_Y - bh;

              const shortPct = b.short  / b.total;
              const medPct   = b.medium / b.total;
              const longPct  = b.long   / b.total;

              const longH  = Math.max(0, longPct  * bh);
              const medH   = Math.max(0, medPct   * bh);
              const shortH = Math.max(0, bh - longH - medH);

              const shortColor = bandColor(BAND_BASE.short,  shortPct - corpusShortPct, maxShortDev);
              const medColor   = bandColor(BAND_BASE.medium, medPct   - corpusMedPct,   maxMedDev);
              const longColor  = bandColor(BAND_BASE.long,   longPct  - corpusLongPct,  maxLongDev);

              return (
                <g key={b.label}
                   onMouseMove={(e) => handleMouseMove(e, b)}
                   onMouseLeave={() => setTooltip(null)}
                   style={{ cursor: 'crosshair' }}>

                  <rect x={bx+2} y={by+2} width={BOOK_W} height={bh}
                        fill="rgba(0,0,0,0.18)" rx="2"/>

                  {/* stacked bands: bottom=short, mid=medium, top=long */}
                  <rect x={bx} y={by + longH + medH} width={BOOK_W} height={shortH}
                        fill={shortColor} rx="1"/>
                  <rect x={bx} y={by + longH} width={BOOK_W} height={medH}
                        fill={medColor}/>
                  <rect x={bx} y={by} width={BOOK_W} height={longH}
                        fill={longColor} rx="1" ry="1"/>

                  <rect x={bx} y={by} width={BOOK_W} height={bh}
                        fill="url(#grain)" rx="1" opacity="0.6"/>
                  <rect x={bx} y={by} width={5} height={bh}
                        fill={SPINE_HL} rx="1" opacity="0.5"/>
                  <rect x={bx+BOOK_W-4} y={by} width={4} height={bh}
                        fill={SPINE_SH} rx="1" opacity="0.4"/>
                  <rect x={bx+2} y={by} width={BOOK_W-4} height={3}
                        fill="rgba(255,255,255,0.75)" rx="1"/>
                  <rect x={bx+1} y={by+bh-5} width={BOOK_W-2} height={5}
                        fill="rgba(0,0,0,0.2)" rx="1"/>

                  {/* Spine label — two horizontal lines at the bottom */}
                  {(() => {
                    const [start, end] = b.label.split('\u2013');
                    const cx      = bx + BOOK_W / 2;
                    const bottomY = by + bh - 7;
                    const fill    = 'rgba(0,0,0,0.6)';
                    const props   = { fill, fontSize: '7', fontFamily: "Georgia,'Times New Roman',serif", textAnchor: 'middle' };
                    return (
                      <>
                        <text x={cx} y={bottomY - 9} {...props}>{start} –</text>
                        <text x={cx} y={bottomY}     {...props}>{end}</text>
                      </>
                    );
                  })()}
                </g>
              );
            })}

            {/* ── scale callout ───────────────────────────────────────── */}
            <line x1={tallestX + BOOK_W / 2} y1={SHELF_Y - tallestH - 6}
                  x2={tallestX + BOOK_W / 2} y2={SHELF_Y - tallestH - 18}
                  stroke="rgba(0,0,0,0.4)" strokeWidth="0.8"/>
            <text x={tallestX + BOOK_W / 2} y={SHELF_Y - tallestH - 22}
                  fill="rgba(0,0,0,0.5)" fontSize="8.5"
                  fontFamily="Georgia,serif" textAnchor="middle">
              {fmt(tallest.total)}
            </text>

            {/* ── shelf ───────────────────────────────────────────────── */}
            <rect x={18} y={SHELF_Y}    width={SVG_W-36} height={20} fill="url(#shelf)" rx="2"/>
            <rect x={18} y={SHELF_Y}    width={SVG_W-36} height={2}  fill="rgba(255,255,255,0.25)" rx="1"/>
            <rect x={18} y={SHELF_Y+20} width={SVG_W-36} height={7}  fill="rgba(0,0,0,0.35)" rx="2"/>

            {/* ── title ───────────────────────────────────────────────── */}
            <text x={SVG_W/2} y={36} fill="rgba(0,0,0,0.75)" fontSize="14"
                  fontFamily="Georgia,'Times New Roman',serif"
                  textAnchor="middle" letterSpacing="3">
              DDB TITLE TOKEN LENGTHS · 1500 – 2024
            </text>
            <text x={SVG_W/2} y={54} fill="rgba(0,0,0,0.38)" fontSize="9"
                  fontFamily="Georgia,serif" textAnchor="middle" letterSpacing="1.5">
              Height · objects per period  ·  Band shade · deviation from corpus-wide average proportion
            </text>

            {/* ── band legend ─────────────────────────────────────────── */}
            <text x={30} y={SVG_H-86} fill="rgba(0,0,0,0.45)" fontSize="7.5"
                  fontFamily="Georgia,serif" letterSpacing="1">
              BANDS (bottom → top)
            </text>
            {[
              { label: 'Short  \u2264 4 tok',  base: BAND_BASE.short  },
              { label: 'Medium 5\u201314 tok', base: BAND_BASE.medium },
              { label: 'Long   \u2265 15 tok', base: BAND_BASE.long   },
            ].map(({ label, base }, i) => (
              <g key={label}>
                <defs>
                  <linearGradient id={`lg${i}`} x1="0" y1="0" x2="1" y2="0">
                    <stop offset="0%"   stopColor={`hsl(0,0%,${base+12}%)`}/>
                    <stop offset="50%"  stopColor={`hsl(0,0%,${base}%)`}/>
                    <stop offset="100%" stopColor={`hsl(0,0%,${base-12}%)`}/>
                  </linearGradient>
                </defs>
                <rect x={30} y={SVG_H-76+i*18} width={32} height={11}
                      fill={`url(#lg${i})`} rx="1"
                      stroke="rgba(0,0,0,0.15)" strokeWidth="0.5"/>
                <text x={67} y={SVG_H-67+i*18} fill="rgba(0,0,0,0.5)" fontSize="8"
                      fontFamily="Georgia,serif">{label}</text>
              </g>
            ))}
            <text x={30}  y={SVG_H-18} fill="rgba(0,0,0,0.28)" fontSize="7"
                  fontFamily="Georgia,serif">\u2190 below avg</text>
            <text x={62}  y={SVG_H-18} fill="rgba(0,0,0,0.28)" fontSize="7"
                  fontFamily="Georgia,serif" textAnchor="middle">above avg \u2192</text>
          </svg>

          {/* Tooltip */}
          {tooltip && (
            <div style={{
              position: 'absolute', left: tooltip.x, top: tooltip.y,
              background: 'rgba(252,249,244,0.98)',
              border: '1px solid rgba(0,0,0,0.2)',
              borderRadius: '3px', padding: '9px 13px',
              color: '#1a1a1a',
              fontFamily: "Georgia,'Times New Roman',serif",
              fontSize: '11px', lineHeight: '1.75',
              pointerEvents: 'none', whiteSpace: 'nowrap',
              zIndex: 20, boxShadow: '0 3px 12px rgba(0,0,0,0.18)',
            }}>
              <div style={{ fontWeight: 'bold', marginBottom: 3, letterSpacing: '0.5px' }}>
                {tooltip.book.label}
              </div>
              <div>{fmt(tooltip.book.total)} objects</div>
              <div style={{ marginTop: 5, color: 'rgba(0,0,0,0.55)', fontSize: '10px' }}>
                Short  (\u2264 4):  {fmt(tooltip.book.short)}  ({((tooltip.book.short  / tooltip.book.total) * 100).toFixed(0)}%)
              </div>
              <div style={{ color: 'rgba(0,0,0,0.55)', fontSize: '10px' }}>
                Medium (5\u201314): {fmt(tooltip.book.medium)} ({((tooltip.book.medium / tooltip.book.total) * 100).toFixed(0)}%)
              </div>
              <div style={{ color: 'rgba(0,0,0,0.55)', fontSize: '10px' }}>
                Long   (\u2265 15): {fmt(tooltip.book.long)}   ({((tooltip.book.long   / tooltip.book.total) * 100).toFixed(0)}%)
              </div>
              <div style={{ marginTop: 5, color: 'rgba(0,0,0,0.4)', fontSize: '10px' }}>
                Median tokens: {tooltip.book.median_all_tokens}
              </div>
            </div>
          )}
        </div>
      );
    }

    ReactDOM.createRoot(document.getElementById('root')).render(<TitleLengthLibrary />);
  </script>
</body>
</html>
"""


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    here = Path(__file__).parent.parent  # repo root

    parser = argparse.ArgumentParser(description="Render title-length visualisation files.")
    parser.add_argument(
        "--json",
        default=str(here / "notes" / "images" / "title-length-analysis.json"),
        help="Path to title-length-analysis.json",
    )
    parser.add_argument(
        "--output-dir",
        default=str(here / "notes" / "images"),
        help="Directory to write .jsx and .html into",
    )
    parser.add_argument(
        "--suffix", type=str, default="",
        help="Suffix appended to output filenames, e.g. '_v2'",
    )
    args = parser.parse_args()

    json_path = Path(args.json)
    out_dir   = Path(args.output_dir)
    suffix    = args.suffix
    out_dir.mkdir(parents=True, exist_ok=True)

    # Load and re-serialise the JSON (compact, non-ASCII escaped for safe embedding)
    data     = json.loads(json_path.read_text(encoding="utf-8"))
    json_str = json.dumps(data, ensure_ascii=True, separators=(",", ":"))

    # Write JSX (static template — data loaded via ES import at runtime)
    jsx_path = out_dir / f"fig_title_lengths{suffix}.jsx"
    jsx_path.write_text(JSX, encoding="utf-8")
    print(f"wrote {jsx_path}")

    # Write HTML (JSON inlined as window.TITLE_DATA)
    html_content = HTML.replace("__JSON_DATA__", json_str)
    html_path = out_dir / f"fig_title_lengths{suffix}_bw.html"
    html_path.write_text(html_content, encoding="utf-8")
    print(f"wrote {html_path}")


if __name__ == "__main__":
    main()
