# Purpose:      Query the DNB SPARQL endpoint to count GND Work records whose
#               preferredNameForTheWork contains each GENERIC_TITLE_WORD, to
#               validate which words are genuinely high-collision and should be
#               excluded from distinctive token selection in link_gnd_works.py.
# Usage:        python scripts/check_generic_title_words.py
#               python scripts/check_generic_title_words.py --delay 2.0
#               python scripts/check_generic_title_words.py --output results/generic_title_words.tsv
# Inputs:       GENERIC_TITLE_WORDS defined in this script
# Outputs:      TSV table of (word, count, keep) printed to stdout and optionally written to file
# Dependencies: requests (pip install requests)
# Assumptions:  Network access to https://sparql.dnb.de/api/dnbgnd

import argparse
import time
import sys
import warnings
from typing import Optional

# urllib3 v2 warns about LibreSSL on macOS — cosmetic only, requests still work
warnings.filterwarnings("ignore", message=".*NotOpenSSLWarning.*")

import requests

ENDPOINT = "https://sparql.dnb.de/api/dnbgnd"

WORK_TYPES = "gndo:Work gndo:MusicalWork gndo:Manuscript"

# Words to validate — candidates for exclusion from distinctive token selection.
# "aufsätze" is queried as "aufs" to match both diacritic and stripped variants.
# Each entry: (display_name, exact_forms)
# Queries use FILTER(LCASE(STR(?l)) = "form") — exact equality, fast via value index.
# Multiple forms cover singular, plural, and common title variants.
# This directly matches Pattern C behaviour in link_gnd_works.py, which also uses
# exact equality. The question answered: how many GND Works have exactly this word
# as their full preferredNameForTheWork?
# German nouns are capitalized. VALUES uses exact literal matching (case-sensitive,
# language-tag-sensitive), so forms must match GND storage exactly.
# Each entry includes: bare singular, bare plural, article+singular, article+plural.
# Both plain string and @de variants are generated by query_count() at runtime.
GENERIC_TITLE_WORDS = [
    ("briefe",     ["Brief", "Briefe", "Der Brief", "Die Briefe"]),
    ("gedichte",   ["Gedicht", "Gedichte", "Das Gedicht", "Die Gedichte"]),
    ("werke",      ["Werk", "Werke", "Das Werk", "Die Werke"]),
    ("schriften",  ["Schrift", "Schriften", "Die Schrift", "Die Schriften"]),
    ("geschichte", ["Geschichte", "Geschichten", "Die Geschichte", "Die Geschichten"]),
    ("bericht",    ["Bericht", "Berichte", "Der Bericht", "Die Berichte"]),
    ("katalog",    ["Katalog", "Kataloge", "Der Katalog", "Die Kataloge"]),
    ("sammlung",   ["Sammlung", "Sammlungen", "Die Sammlung", "Die Sammlungen"]),
    ("aufsätze",   ["Aufsatz", "Aufsätze", "Der Aufsatz", "Die Aufsätze"]),
    ("texte",      ["Text", "Texte", "Der Text", "Die Texte"]),
    ("band",       ["Band", "Bände", "Der Band", "Die Bände"]),
    ("teil",       ["Teil", "Teile", "Der Teil", "Die Teile"]),
    ("heft",       ["Heft", "Hefte", "Das Heft", "Die Hefte"]),
    ("nummer",     ["Nummer", "Nummern", "Die Nummer", "Die Nummern"]),
    ("jahrgang",   ["Jahrgang", "Jahrgänge", "Der Jahrgang", "Die Jahrgänge"]),
]

QUERY_TEMPLATE = """\
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT (COUNT(?w) AS ?n) WHERE {{
  VALUES ?t {{ {work_types} }}
  VALUES ?l {{ {values} }}
  ?w a ?t .
  ?w gndo:preferredNameForTheWork ?l .
}}"""


def query_count(forms: list, timeout: int) -> Optional[int]:
    # GND stores preferredNameForTheWork as plain literals (no language tag)
    values = " ".join('"{}"'.format(f) for f in forms)
    sparql = QUERY_TEMPLATE.format(work_types=WORK_TYPES, values=values)
    try:
        r = requests.post(
            ENDPOINT,
            data={"query": sparql},
            headers={"Accept": "application/sparql-results+json"},
            timeout=timeout,
        )
        r.raise_for_status()
        bindings = r.json()["results"]["bindings"]
        if bindings:
            return int(bindings[0]["n"]["value"])
        return 0
    except Exception as e:
        print(f"  ERROR: {e}", file=sys.stderr)
        return None


def main():
    parser = argparse.ArgumentParser(
        description="Count GND Work records per GENERIC_TITLE_WORD"
    )
    parser.add_argument(
        "--delay", type=float, default=1.0,
        help="Seconds to wait between requests (default: 1.0)"
    )
    parser.add_argument(
        "--timeout", type=int, default=120,
        help="Request timeout in seconds (default: 120)"
    )
    parser.add_argument(
        "--output", type=str, default=None,
        help="Optional path to write TSV output"
    )
    args = parser.parse_args()

    rows = []
    print(f"{'Word':<15} {'Filter':<12} {'Count':>8}")
    print("-" * 38)

    for word, forms in GENERIC_TITLE_WORDS:
        print(f"  querying '{word}'...", end=" ", flush=True)
        count = query_count(forms, args.timeout)
        status = f"{count:,}" if count is not None else "ERROR"
        print(status)
        rows.append((word, forms, count))
        time.sleep(args.delay)

    print()
    print(f"{'Word':<15} {'Count':>8}  Keep?")
    print("-" * 38)
    for word, forms, count in rows:
        if count is None:
            keep = "?"
            count_str = "ERROR"
        else:
            keep = "No" if count >= 100 else "Yes (low collision)"
            count_str = f"{count:,}"
        print(f"{word:<15} {count_str:>8}  {keep}")

    if args.output:
        with open(args.output, "w") as f:
            f.write("word\tforms\tcount\tkeep\n")
            for word, forms, count in rows:
                keep = "no" if (count or 0) >= 100 else "yes"
                f.write(f"{word}\t{','.join(forms)}\t{count or ''}\t{keep}\n")
        print(f"\nResults written to {args.output}")
        print(f"\nResults written to {args.output}")


if __name__ == "__main__":
    main()
