/**
 * fig_title_lengths.jsx
 *
 * Library of leather-bound books visualizing DDB title token lengths
 * by 25-year period.
 *
 *   Height of each book  →  number of objects in the period
 *   Leather patina       →  median title length in tokens
 *
 * Data source: title-length-analysis.json  (scripts/sr10_analyse_title_lengths.py)
 * Generated by: scripts/sr10_render_title_viz.py
 * Usage: import and render <TitleLengthLibrary /> in any React app.
 */

import React, { useRef, useState } from 'react';
import rawData from './title-length-analysis.json';

// ── layout constants ──────────────────────────────────────────────────────────

const BOOK_W    = 44;
const BOOK_GAP  = 5;
const MAX_BOOK_H = 300;
const MIN_BOOK_H = 28;
const SHELF_Y   = 415;
const START_X   = 60;
const SVG_H     = 510;

// ── colour helpers ────────────────────────────────────────────────────────────

/**
 * Map median token count (data range: 6–15) to a leather HSL colour.
 *   t = 0  →  pale tan        (short modern titles, lightly patinated)
 *   t = 1  →  dark mahogany   (long baroque titles, heavily patinated)
 */
function patina(median) {
  const t = Math.min(1, Math.max(0, (median - 6) / 9));
  const h = (27 - t * 12).toFixed(1);   // 27° warm tan → 15° mahogany
  const s = (45 + t * 23).toFixed(1);   // 45% → 68%
  const l = (54 - t * 34).toFixed(1);   // 54% → 20%
  return `hsl(${h},${s}%,${l}%)`;
}

function patinaHighlight(median) {
  const t = Math.min(1, Math.max(0, (median - 6) / 9));
  const h = (27 - t * 12).toFixed(1);
  const s = (30 + t * 15).toFixed(1);
  const l = (68 - t * 28).toFixed(1);
  return `hsl(${h},${s}%,${l}%)`;
}

function fmt(n) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000)     return `${(n / 1_000).toFixed(1)}k`;
  return String(n);
}

// ── component ─────────────────────────────────────────────────────────────────

export default function TitleLengthLibrary() {
  const containerRef = useRef(null);
  const [tooltip, setTooltip]   = useState(null);

  const buckets = Object.entries(rawData.bucketed)
    .filter(([, v]) => v.total > 100)
    .map(([label, v]) => ({ label, ...v }));

  const maxTotal = Math.max(...buckets.map(b => b.total));
  const SVG_W = START_X * 2 + buckets.length * (BOOK_W + BOOK_GAP) - BOOK_GAP;

  const bookH = (total) => Math.max(MIN_BOOK_H, (total / maxTotal) * MAX_BOOK_H);

  function handleMouseMove(e, book) {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    setTooltip({ book, x: e.clientX - rect.left + 14, y: e.clientY - rect.top - 10 });
  }

  return (
    <div
      ref={containerRef}
      style={{ position: 'relative', display: 'inline-block', background: '#0f0804' }}
    >
      <svg width={SVG_W} height={SVG_H} viewBox={`0 0 ${SVG_W} ${SVG_H}`}
           style={{ display: 'block' }}>
        <defs>
          {/* Leather grain: faint diagonal scratches */}
          <pattern id="grain" width="4" height="60" patternUnits="userSpaceOnUse">
            <line x1="1"   y1="0" x2="0.5" y2="60"
                  stroke="rgba(0,0,0,0.09)"       strokeWidth="0.6"/>
            <line x1="3.2" y1="0" x2="2.8" y2="60"
                  stroke="rgba(255,255,255,0.04)"  strokeWidth="0.4"/>
          </pattern>

          {/* Worn oak shelf */}
          <linearGradient id="shelf" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%"   stopColor="#7a4e22"/>
            <stop offset="18%"  stopColor="#5c3510"/>
            <stop offset="100%" stopColor="#2a1508"/>
          </linearGradient>

          {/* Dark oak-panel wall */}
          <linearGradient id="wall" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%"   stopColor="#1c0d06"/>
            <stop offset="100%" stopColor="#0f0804"/>
          </linearGradient>
        </defs>

        {/* ── background ─────────────────────────────────────────────────── */}
        <rect width={SVG_W} height={SVG_H} fill="url(#wall)"/>

        {/* Subtle horizontal panelling lines */}
        {Array.from({ length: 7 }, (_, i) => (
          <line key={i}
                x1="0" y1={i * 65 + 65} x2={SVG_W} y2={i * 65 + 65}
                stroke="rgba(255,255,255,0.012)" strokeWidth="1"/>
        ))}

        {/* ── books ──────────────────────────────────────────────────────── */}
        {buckets.map((b, i) => {
          const bh  = bookH(b.total);
          const bx  = START_X + i * (BOOK_W + BOOK_GAP);
          const by  = SHELF_Y - bh;
          const base = patina(b.median_all_tokens);
          const hl   = patinaHighlight(b.median_all_tokens);

          return (
            <g key={b.label}
               onMouseMove={(e) => handleMouseMove(e, b)}
               onMouseLeave={() => setTooltip(null)}
               style={{ cursor: 'crosshair' }}>

              {/* Drop shadow */}
              <rect x={bx + 3} y={by + 3} width={BOOK_W} height={bh}
                    fill="rgba(0,0,0,0.5)" rx="2"/>

              {/* Book body */}
              <rect x={bx} y={by} width={BOOK_W} height={bh}
                    fill={base} rx="2" ry="2"/>

              {/* Leather grain overlay */}
              <rect x={bx} y={by} width={BOOK_W} height={bh}
                    fill="url(#grain)" rx="2" opacity="0.75"/>

              {/* Left spine highlight — light catches the raised edge */}
              <rect x={bx} y={by} width={5} height={bh}
                    fill={hl} rx="2" opacity="0.55"/>

              {/* Right edge shadow */}
              <rect x={bx + BOOK_W - 4} y={by} width={4} height={bh}
                    fill="rgba(0,0,0,0.35)" rx="2"/>

              {/* Top cap */}
              <rect x={bx} y={by} width={BOOK_W} height={4}
                    fill={hl} rx="2" opacity="0.65"/>

              {/* Bottom foot — binding wear */}
              <rect x={bx + 1} y={by + bh - 6} width={BOOK_W - 2} height={6}
                    fill="rgba(0,0,0,0.25)" rx="1"/>

              {/* Spine label — two horizontal lines at the bottom */}
              {(() => {
                const [start, end] = b.label.split('\u2013');
                const cx      = bx + BOOK_W / 2;
                const bottomY = by + bh - 7;
                const fill    = 'rgba(255,215,110,0.62)';
                const props   = { fill, fontSize: '7', fontFamily: "Georgia,'Times New Roman',serif", textAnchor: 'middle' };
                return (
                  <>
                    <text x={cx} y={bottomY - 9} {...props}>{start} –</text>
                    <text x={cx} y={bottomY}     {...props}>{end}</text>
                  </>
                );
              })()}
            </g>
          );
        })}

        {/* ── shelf ──────────────────────────────────────────────────────── */}
        <rect x={18} y={SHELF_Y}      width={SVG_W - 36} height={22}
              fill="url(#shelf)" rx="2"/>
        {/* Top edge highlight */}
        <rect x={18} y={SHELF_Y}      width={SVG_W - 36} height={2}
              fill="rgba(255,185,70,0.22)" rx="1"/>
        {/* Undershadow */}
        <rect x={18} y={SHELF_Y + 22} width={SVG_W - 36} height={9}
              fill="rgba(0,0,0,0.65)" rx="2"/>

        {/* ── title ──────────────────────────────────────────────────────── */}
        <text x={SVG_W / 2} y={36}
              fill="rgba(235,205,140,0.75)"
              fontSize="14"
              fontFamily="Georgia,'Times New Roman',serif"
              textAnchor="middle"
              letterSpacing="3">
          DDB TITLE TOKEN LENGTHS · 1500 – 2024
        </text>
        <text x={SVG_W / 2} y={54}
              fill="rgba(175,140,85,0.45)"
              fontSize="9"
              fontFamily="Georgia,serif"
              textAnchor="middle"
              letterSpacing="1.5">
          Height · objects per 25-year period  ·  Patina · median title length in tokens
        </text>

        {/* ── patina legend ──────────────────────────────────────────────── */}
        <text x={SVG_W - 192} y={SVG_H - 80}
              fill="rgba(185,148,82,0.6)"
              fontSize="7.5"
              fontFamily="Georgia,serif"
              letterSpacing="1.2">
          PATINA · MEDIAN TOKENS
        </text>
        {[6, 8, 10, 12, 14].map((t, i) => (
          <g key={t}>
            <rect x={SVG_W - 192 + i * 29} y={SVG_H - 70}
                  width={23} height={15} fill={patina(t)} rx="1"/>
            <text x={SVG_W - 192 + i * 29 + 11.5} y={SVG_H - 50}
                  fill="rgba(185,148,82,0.55)"
                  fontSize="8"
                  fontFamily="Georgia,serif"
                  textAnchor="middle">
              {t}
            </text>
          </g>
        ))}
        <text x={SVG_W - 192} y={SVG_H - 40}
              fill="rgba(160,125,65,0.4)"
              fontSize="7.5"
              fontFamily="Georgia,serif">
          modern
        </text>
        <text x={SVG_W - 192 + 4 * 29 + 12} y={SVG_H - 40}
              fill="rgba(160,125,65,0.4)"
              fontSize="7.5"
              fontFamily="Georgia,serif"
              textAnchor="end">
          baroque
        </text>
      </svg>

      {/* ── floating tooltip ─────────────────────────────────────────────── */}
      {tooltip && (
        <div style={{
          position:      'absolute',
          left:          tooltip.x,
          top:           tooltip.y,
          background:    'rgba(10,6,2,0.97)',
          border:        '1px solid rgba(210,165,70,0.32)',
          borderRadius:  '3px',
          padding:       '9px 13px',
          color:         '#e0c880',
          fontFamily:    "Georgia,'Times New Roman',serif",
          fontSize:      '11px',
          lineHeight:    '1.75',
          pointerEvents: 'none',
          whiteSpace:    'nowrap',
          zIndex:        20,
          boxShadow:     '0 3px 16px rgba(0,0,0,0.75)',
        }}>
          <div style={{ fontWeight: 'bold', marginBottom: 3, letterSpacing: '0.5px' }}>
            {tooltip.book.label}
          </div>
          <div>{fmt(tooltip.book.total)} objects</div>
          <div style={{ marginTop: 5, color: 'rgba(200,160,85,0.75)', fontSize: '10px' }}>
            Short  (≤ 4 tok): {fmt(tooltip.book.short)} &nbsp;
            ({((tooltip.book.short  / tooltip.book.total) * 100).toFixed(0)}%)
          </div>
          <div style={{ color: 'rgba(200,160,85,0.75)', fontSize: '10px' }}>
            Medium (5–14):    {fmt(tooltip.book.medium)} &nbsp;
            ({((tooltip.book.medium / tooltip.book.total) * 100).toFixed(0)}%)
          </div>
          <div style={{ color: 'rgba(200,160,85,0.75)', fontSize: '10px' }}>
            Long   (≥ 15 tok): {fmt(tooltip.book.long)} &nbsp;
            ({((tooltip.book.long   / tooltip.book.total) * 100).toFixed(0)}%)
          </div>
          <div style={{ marginTop: 5, color: 'rgba(185,148,75,0.6)', fontSize: '10px' }}>
            Median tokens: {tooltip.book.median_all_tokens}
          </div>
        </div>
      )}
    </div>
  );
}
